import type { Quiz } from "./mock-data";

const scoreExpression = [
  "q1",
  "(q2 == false ? 4 : 0)",
  "q3",
  "q5",
  "(q6 == false ? 3 : 0)",
  "q7",
  "q9",
  "(q10 == false ? 4 : 0)",
  "q11",
  "q13",
  "(q14 == false ? 4 : 0)",
  "q15",
  "q17",
  "(q18 == false ? 4 : 0)",
  "q20",
  "(q21 == false ? 3 : 0)",
  "q23",
  "(q24 == false ? 3 : 0)",
  "(q27 == false ? 2 : 0)",
  "q28",
].join(" + ");

const option = (questionId: string, index: number, label: string) => ({
  id: `${questionId}_opt_${index}`,
  label,
  value: index,
});

const textOption = (questionId: string, index: number, label: string) => ({
  id: `${questionId}_opt_${index}`,
  label,
  value: label,
});

export const IPA_DISCOVERY_QUIZ: Quiz = {
  id: "quiz-ipa-discovery",
  orgId: "org-1",
  title: "IPA Discovery Quiz",
  description:
    "Identify patient access, onboarding, care coordination, and operational automation opportunities across an IPA network.",
  slug: "ipa-discovery",
  published: true,
  gateResults: false,
  price: 0,
  questions: [
    {
      id: "q1",
      type: "single",
      text: "How often do patients report difficulty reaching your network by phone during business hours?",
      key: "q1",
      category: "Patient Access & Communication",
      helpText: "How patients reach your IPA, and what happens when they cannot.",
      required: true,
      options: ["Rarely", "Sometimes", "Often", "Very Often", "Constantly"].map((label, index) =>
        option("q1", index, label),
      ),
      defaultNextQuestionId: "q2",
    },
    {
      id: "q2",
      type: "yes_no",
      text: "Do you have any coverage for after-hours patient calls - evenings, weekends, and holidays?",
      key: "q2",
      category: "Patient Access & Communication",
      required: true,
      defaultNextQuestionId: "q3",
    },
    {
      id: "q3",
      type: "single",
      text: "How quickly does your team follow up with patients who leave a voicemail or message?",
      key: "q3",
      category: "Patient Access & Communication",
      required: true,
      options: ["Within 1 hr", "Same day", "Next day", "2-3 days", "No system"].map((label, index) =>
        option("q3", index, label),
      ),
      defaultNextQuestionId: "q4",
    },
    {
      id: "q4",
      type: "multi",
      text: "Which patient communication challenges does your IPA face? Select all that apply.",
      key: "q4",
      category: "Patient Access & Communication",
      required: true,
      options: [
        "High call volume overwhelming front desk",
        "No automated appointment reminders",
        "No after-hours answering solution",
        "Patients cannot self-schedule online",
        "No automated recall / follow-up system",
        "Language barriers with patient population",
        "No way to send mass health alerts or updates",
      ].map((label, index) => textOption("q4", index, label)),
      defaultNextQuestionId: "q5",
    },
    {
      id: "q5",
      type: "single",
      text: "How structured and consistent is your new patient onboarding process across member physicians?",
      key: "q5",
      category: "Patient Onboarding & Enrollment",
      helpText: "The first 30 days set the tone for the entire patient relationship.",
      required: true,
      options: ["Fully Standardized", "Mostly Consistent", "Varies by Member", "Minimal Structure", "No Process"].map(
        (label, index) => option("q5", index, label),
      ),
      defaultNextQuestionId: "q6",
    },
    {
      id: "q6",
      type: "yes_no",
      text: "Do new patients receive an automated welcome sequence - orientation to the association, care team intro, and what to expect?",
      key: "q6",
      category: "Patient Onboarding & Enrollment",
      required: true,
      defaultNextQuestionId: "q7",
    },
    {
      id: "q7",
      type: "single",
      text: "How effectively does your IPA collect new patient intake forms, health histories, and consents before their first visit?",
      key: "q7",
      category: "Patient Onboarding & Enrollment",
      required: true,
      options: ["Fully Digital", "Mostly Digital", "Mixed Paper/Digital", "Mostly Paper", "All Paper"].map(
        (label, index) => option("q7", index, label),
      ),
      defaultNextQuestionId: "q8",
    },
    {
      id: "q8",
      type: "multi",
      text: "Which new patient onboarding gaps exist in your IPA today? Select all that apply.",
      key: "q8",
      category: "Patient Onboarding & Enrollment",
      required: true,
      options: [
        "No standardized onboarding across member physicians",
        "Paper-based intake still in use",
        "Patients not reminded to complete intake before visit",
        "No welcome communication after enrollment",
        "Care team not introduced to new patients",
        "Insurance/eligibility verification is manual",
        "New patients frequently no-show for first appointment",
        "No structured handoff from enrollment to first visit",
      ].map((label, index) => textOption("q8", index, label)),
      defaultNextQuestionId: "q9",
    },
    {
      id: "q9",
      type: "single",
      text: "What percentage of your attributed patient panel completes an annual wellness visit each year?",
      key: "q9",
      category: "Wellness Visits & Preventive Care",
      helpText: "Annual wellness visits are one of the IPA's most measurable value drivers.",
      required: true,
      options: ["Over 80%", "60-80%", "40-60%", "20-40%", "Under 20% / Unknown"].map((label, index) =>
        option("q9", index, label),
      ),
      defaultNextQuestionId: "q10",
    },
    {
      id: "q10",
      type: "yes_no",
      text: "Do you have an automated system that identifies patients who are due for their annual wellness visit and proactively reaches out to schedule them?",
      key: "q10",
      category: "Wellness Visits & Preventive Care",
      required: true,
      defaultNextQuestionId: "q11",
    },
    {
      id: "q11",
      type: "single",
      text: "How well does your IPA track and close preventive care gaps - screenings, immunizations, mammograms, colonoscopies, A1c checks?",
      key: "q11",
      category: "Wellness Visits & Preventive Care",
      required: true,
      options: ["Excellent", "Good", "Inconsistent", "Poor", "No Visibility"].map((label, index) =>
        option("q11", index, label),
      ),
      defaultNextQuestionId: "q12",
    },
    {
      id: "q12",
      type: "multi",
      text: "Which preventive care and wellness challenges does your IPA struggle with most? Select all that apply.",
      key: "q12",
      category: "Wellness Visits & Preventive Care",
      required: true,
      options: [
        "Patients overdue for annual wellness visits",
        "Low completion on preventive screenings",
        "No system to track which patients have open care gaps",
        "Immunization rates below target",
        "Diabetic patients not getting A1c or eye exams",
        "Hypertensive patients not getting regular BP checks",
        "No proactive outreach for overdue preventive care",
        "Care gap data lives in EHR but no one acts on it",
      ].map((label, index) => textOption("q12", index, label)),
      defaultNextQuestionId: "q13",
    },
    {
      id: "q13",
      type: "single",
      text: "When a patient receives a new diagnosis - from a specialist, urgent care, or ER visit - how reliably does that information reach the IPA so monitoring and follow-up can begin?",
      key: "q13",
      category: "Care Plans & Chronic Disease Management",
      helpText: "Care plans only work if patients follow them, and most IPAs never find out about new diagnoses until it is too late to act.",
      required: true,
      options: ["Always Informed", "Usually Informed", "Sometimes Informed", "Rarely Informed", "No System Exists"].map(
        (label, index) => option("q13", index, label),
      ),
      defaultNextQuestionId: "q14",
    },
    {
      id: "q14",
      type: "yes_no",
      text: "When a specialist, ER, or outside provider recommends a new treatment, screening, or medication for a patient, does the IPA have a structured process to receive that information and act on it?",
      key: "q14",
      category: "Care Plans & Chronic Disease Management",
      required: true,
      defaultNextQuestionId: "q15",
    },
    {
      id: "q15",
      type: "single",
      text: "How proactive versus reactive is your IPA today - are you identifying patients who need intervention before a crisis, or responding after one has occurred?",
      key: "q15",
      category: "Care Plans & Chronic Disease Management",
      required: true,
      options: ["Fully Proactive", "Mostly Proactive", "About Equal", "Mostly Reactive", "Fully Reactive"].map(
        (label, index) => option("q15", index, label),
      ),
      defaultNextQuestionId: "q16",
    },
    {
      id: "q16",
      type: "long_text",
      text: "In a perfect world, how would your IPA want to be notified when a patient is diagnosed with a new condition, prescribed a new treatment, or recommended a new screening - and what would you do with that information?",
      key: "q16",
      category: "Care Plans & Chronic Disease Management",
      required: true,
      defaultNextQuestionId: "q17",
    },
    {
      id: "q17",
      type: "single",
      text: "How consistently are care plans documented, shared with patients, and followed up on across your IPA?",
      key: "q17",
      category: "Care Plans & Chronic Disease Management",
      required: true,
      options: ["Consistently", "Mostly", "Inconsistently", "Rarely", "Not Standardized"].map((label, index) =>
        option("q17", index, label),
      ),
      defaultNextQuestionId: "q18",
    },
    {
      id: "q18",
      type: "yes_no",
      text: "Do chronic disease patients receive automated between-visit touchpoints - reminders, check-ins, or medication adherence prompts?",
      key: "q18",
      category: "Care Plans & Chronic Disease Management",
      required: true,
      defaultNextQuestionId: "q19",
    },
    {
      id: "q19",
      type: "multi",
      text: "Which chronic care and care plan challenges apply to your IPA? Select all that apply.",
      key: "q19",
      category: "Care Plans & Chronic Disease Management",
      required: true,
      options: [
        "New diagnoses from outside providers not reaching the IPA",
        "Specialist or ER recommendations not looping back to the IPA",
        "No process to enroll newly diagnosed patients into monitoring",
        "Care plans documented but patients do not understand them",
        "No between-visit touchpoints for chronic patients",
        "Medication adherence is not being monitored",
        "High-risk patients not flagged until they deteriorate",
        "Post-ER or post-discharge follow-up is inconsistent",
        "No structured escalation path for worsening symptoms",
        "Transition of care handoffs are manual and often missed",
        "No visibility into which patients are off-track",
      ].map((label, index) => textOption("q19", index, label)),
      defaultNextQuestionId: "q20",
    },
    {
      id: "q20",
      type: "single",
      text: "What is your current no-show or late-cancellation rate?",
      key: "q20",
      category: "Scheduling & No-Shows",
      helpText: "Empty slots cost revenue. No-shows cost twice.",
      required: true,
      options: ["Under 5%", "5-10%", "10-15%", "15-20%", "Over 20%"].map((label, index) =>
        option("q20", index, label),
      ),
      defaultNextQuestionId: "q21",
    },
    {
      id: "q21",
      type: "yes_no",
      text: "Do patients currently have a way to self-schedule or reschedule appointments online or via text?",
      key: "q21",
      category: "Scheduling & No-Shows",
      required: true,
      defaultNextQuestionId: "q22",
    },
    {
      id: "q22",
      type: "multi",
      text: "Which scheduling problems cost your IPA the most? Select all that apply.",
      key: "q22",
      category: "Scheduling & No-Shows",
      required: true,
      options: [
        "High no-show rate",
        "Staff time wasted on manual reminder calls",
        "Last-minute cancellations with no one to fill the slot",
        "Patients scheduling with wrong provider or location",
        "No automated follow-up for missed appointments",
        "Referral appointments not being confirmed or tracked",
        "Follow-up visits after chronic care visits not being scheduled",
      ].map((label, index) => textOption("q22", index, label)),
      defaultNextQuestionId: "q23",
    },
    {
      id: "q23",
      type: "single",
      text: "How effectively do referrals get tracked from the moment they are sent to confirmed appointment completion?",
      key: "q23",
      category: "Care Coordination & Referrals",
      helpText: "Referral leakage is one of the biggest revenue leaks most IPAs never see.",
      required: true,
      options: ["Fully Tracked", "Mostly Tracked", "Inconsistent", "Rarely Tracked", "No System"].map((label, index) =>
        option("q23", index, label),
      ),
      defaultNextQuestionId: "q24",
    },
    {
      id: "q24",
      type: "yes_no",
      text: "Do you have a system that alerts your team when a referred patient has not scheduled within a set timeframe?",
      key: "q24",
      category: "Care Coordination & Referrals",
      required: true,
      defaultNextQuestionId: "q25",
    },
    {
      id: "q25",
      type: "multi",
      text: "Which care coordination gaps exist in your IPA today? Select all that apply.",
      key: "q25",
      category: "Care Coordination & Referrals",
      required: true,
      options: [
        "Referrals sent but not confirmed or tracked",
        "Patients falling through the cracks between providers",
        "No post-discharge follow-up system",
        "Chronic care patients not proactively contacted between visits",
        "Test results not triggering timely patient outreach",
        "No care gap closure workflows",
        "Specialist-to-PCP communication is manual and slow",
        "Transition of care handoffs are frequently dropped",
      ].map((label, index) => textOption("q25", index, label)),
      defaultNextQuestionId: "q26",
    },
    {
      id: "q26",
      type: "single",
      text: "How much of your administrative staff's time goes to tasks that could be automated - reminder calls, form collection, referral tracking, status updates?",
      key: "q26",
      category: "Operations Staff & Growth",
      helpText: "What is eating your team's time, limiting scale, and stalling growth.",
      required: true,
      options: ["Very Little", "Some", "About Half", "Majority", "Almost Everything"].map((label, index) =>
        option("q26", index, label),
      ),
      defaultNextQuestionId: "q27",
    },
    {
      id: "q27",
      type: "yes_no",
      text: "Is your IPA actively tracking quality metrics - HEDIS, Stars, or value-based contract performance - in a way your team can act on in real time?",
      key: "q27",
      category: "Operations Staff & Growth",
      required: true,
      defaultNextQuestionId: "q28",
    },
    {
      id: "q28",
      type: "single",
      text: "How satisfied are you with your current rate of new patient acquisition and inactive patient re-engagement?",
      key: "q28",
      category: "Operations Staff & Growth",
      required: true,
      options: ["Very Satisfied", "Satisfied", "Neutral", "Unsatisfied", "Very Unsatisfied"].map((label, index) =>
        option("q28", index, label),
      ),
      defaultNextQuestionId: "q29",
    },
    {
      id: "q29",
      type: "long_text",
      text: "If you could solve one operational or patient care problem in your IPA over the next 90 days, what would it be?",
      key: "q29",
      category: "Operations Staff & Growth",
      required: true,
      defaultNextQuestionId: "finish",
    },
  ],
  calculatedFields: [
    {
      id: "ipa_score",
      key: "ipa_opportunity_score",
      label: "IPA Opportunity Score",
      type: "number",
      expression: scoreExpression,
      description: "Higher scores indicate more urgent automation and workflow opportunities.",
    },
  ],
  outcomes: [
    {
      id: "ipa_critical",
      type: "threshold",
      label: "Critical Automation Opportunity",
      message:
        "Your responses point to multiple high-priority gaps across patient access, care coordination, quality tracking, and administrative workflows. This is a strong fit for a phased IPA automation build.",
      severity: "fail",
      metric: "ipa_opportunity_score",
      operator: ">=",
      threshold: 42,
    },
    {
      id: "ipa_phase_one",
      type: "threshold",
      label: "Phase 1 Automation Fit",
      message:
        "Your IPA has enough operational friction to justify a focused first build. Start with the highest-volume workflows, prove the lift, then expand across the network.",
      severity: "caution",
      metric: "ipa_opportunity_score",
      operator: ">=",
      threshold: 24,
    },
    {
      id: "ipa_quick_wins",
      type: "threshold",
      label: "Quick Win Opportunity",
      message:
        "Your IPA appears to have a more controlled operating baseline, but there are still targeted automation opportunities worth packaging as fast ROI wins.",
      severity: "pass",
      metric: "ipa_opportunity_score",
      operator: ">=",
      threshold: 0,
    },
  ],
};
