services:
  - type: web
    name: quiz-pro-quo
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_APP_URL
        value: https://qproquo.howstud.io
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
